name: .NET

on:
  # Configureer triggers voor een push op de main branch
  push:
    branches:
      - main

  # Configureer triggers voor een pull request
  pull_request:
    branches:
      - main
 
  # Configureer een trigger voor een handmatige build
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      WORKDIR: "./src/HelloWorld"
      CONFIG: "Release"
      AZURE_FUNCTIONAPP_NAME: "HelloWorld-MartijnK"
    defaults:
      run:
        working-directory: ${{env.WORKDIR}}

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Build
      run: dotnet build --no-restore --output ./output
      shell: bash

    - name: Test
      working-directory: ${{ env.WORKDIR }}.UnitTests
      run: |
        dotnet test --configuration ${{ env.CONFIG }}
      shell: bash

    - name: Publish
      run: |
        dotnet publish -c ${{ env.CONFIG }}
      shell: bash

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{env.AZURE_FUNCTIONAPP_NAME}}
        package: ${{env.WORKDIR}}/bin/${{env.CONFIG}}/net6.0/publish
        publish-profile: ${{ secrets.HELLOWORLD20220916153654_FFFF }}
